[[inputs.http]]
  name_override = "vdm_xp_state"
  urls = [
    "https://172.30.216.73:8443/api/v1/models/VdmXpState?attr=xpId,macDomainIndex,status,neStatus,regTime,lastStateChangeTime,lastResponseTime,roundTripTime,vdmRxLevelDeviation,xpTxLevel,repliedPackets,unrepliedPackets,contiguousFailures,polls,lowPrioPollCnt,usSessionIndex,dsSessionIndex,usSessionId"
  ]
  method = "GET"
  interval = "15m"
  timeout = "10s"
  insecure_skip_verify = true
  data_format = "json"
  tag_keys = ["xpId", "usSessionId"]

  [inputs.http.headers]
    Accept = "application/json"
    Authorization = "Bearer ApiKey-1dde1d0b-76e7-42cd-82f2-6b79a2cd2624"

[[inputs.http]]
  name_override = "vdm_manager_state"
  urls = [
    "https://172.30.216.73:8443/api/v1/models/VdmManagerState?attr=vdmId,statusText,totalXpCount,totalRpdCount,errorXpCount,errorRpdCount,warningXpCount,warningRpdCount,noticeXpCount,noticeRpdCount,okXpCount,okRpdCount"
  ]
  method = "GET"
  interval = "15m"
  timeout = "10s"
  insecure_skip_verify = true
  data_format = "json"
  tag_keys = ["vdmId", "statusText"]

  [inputs.http.headers]
    Accept = "application/json"
    Authorization = "Bearer ApiKey-1dde1d0b-76e7-42cd-82f2-6b79a2cd2624"
